name: Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  BINARY_NAME: plumeimpactor
  BINARY_NAME_CLI: plumesign
  BUNDLE_NAME: Impactor

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            arch: x86_64
          - os: ubuntu-22.04-arm
            arch: aarch64
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Use Wild linker
        uses: davidlattimore/wild-action@latest
      - uses: snok/install-poetry@v1
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install apt packages
        run: sudo apt-get update && sudo apt-get install -y flatpak flatpak-builder ...

      - name: Build binaries
        run: |
          make linux PROFILE=release APPIMAGE=1

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}-linux-${{ matrix.arch }}
          path: dist/*

  build-windows:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-gnu
      - run: sudo apt-get install -y mingw-w64

      - name: Build
        run: |
          cargo build --bins --workspace --release --target x86_64-pc-windows-gnu
          mkdir -p dist
          cp target/x86_64-pc-windows-gnu/release/*.exe dist/

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}-windows
          path: dist/*.exe

  build-windows-installer:
    runs-on: windows-latest
    needs: [build-windows]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}-windows
          path: dist
      - run: choco install nsis.portable

      - run: |
          mkdir dist\nsis
          copy package\windows\* dist\nsis\
          copy dist\Impactor-windows-x86_64-portable.exe dist\nsis\plumeimpactor.exe
          makensis dist\nsis\installer.nsi
          move dist\nsis\installer.exe dist\Impactor-windows-x86_64-setup.exe

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}-windows-installer
          path: dist/Impactor-windows-x86_64-setup.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      - run: make macos PROFILE=release BUNDLE=1

      - uses: apple-actions/import-codesign-certs@v5
        with:
          p12-file-base64: ${{ secrets.DEV_ID_P12_BASE64 }}
          p12-password: ${{ secrets.DEV_ID_P12_PASSWORD }}

      - run: codesign --deep --force --options runtime --sign "${{ secrets.DEV_ID_IDENTITY_NAME }}" dist/Impactor.app

      - run: brew install create-dmg

      - run: |
          mkdir -p dist/dmg
          mv dist/Impactor.app dist/dmg/
          create-dmg \
            --volname "${{ env.BUNDLE_NAME }}" \
            --background "package/macos/background.png" \
            --window-pos 200 120 \
            --window-size 510 350 \
            --icon-size 100 \
            --icon "${{ env.BUNDLE_NAME }}.app" 160 155 \
            --hide-extension "${{ env.BUNDLE_NAME }}.app" \
            --app-drop-link 350 155 \
            dist/${{ env.BUNDLE_NAME }}-macos-arm64.dmg dist/dmg

      - run: |
          xcrun notarytool submit dist/${{ env.BUNDLE_NAME }}-macos-arm64.dmg --apple-id "${{ secrets.APPLE_ID_EMAIL }}" --password "${{ secrets.APPLE_ID_PASSWORD }}" --team-id "${{ secrets.APPLE_ID_TEAM }}" --wait
          xcrun stapler staple dist/${{ env.BUNDLE_NAME }}-macos-arm64.dmg

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}-macos-arm64
          path: dist/${{ env.BUNDLE_NAME }}-macos-arm64.dmg

  release:
    runs-on: ubuntu-22.04
    needs: [build-linux, build-windows-installer, build-macos]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}-linux-x86_64
          path: prepare/

      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}-linux-aarch64
          path: prepare/

      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}-windows
          path: prepare/

      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}-windows-installer
          path: prepare/

      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}-macos-arm64
          path: prepare/

      - run: |
          mkdir -p upload
          shopt -s globstar
          mv prepare/**/*.* upload/

      - id: get_version
        run: |
          VERSION=$(awk '/\[workspace.package\]/,/^$/' Cargo.toml | sed -nE 's/version *= *"([^"]*)".*/\1/p')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - uses: softprops/action-gh-release@v2
        with:
          name: v${{ steps.get_version.outputs.version }}
          tag_name: v${{ steps.get_version.outputs.version }}
          files: upload/*
          generate_release_notes: true
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
