name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      build_linux:
        description: Build Linux
        type: boolean
        required: true
        default: true
      build_windows:
        description: Build Windows
        type: boolean
        required: true
        default: true
      build_macos_arm64:
        description: Build macOS Silicon / ARM64
        type: boolean
        required: true
        default: true
      build_macos_intel:
        description: Build macOS Intel
        type: boolean
        required: true
        default: true

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  BINARY_NAME: plumeimpactor
  BINARY_NAME_CLI: plumesign
  BUNDLE_NAME: Impactor

jobs:
  build-linux:
    if: ${{ github.event_name == 'push' || inputs.build_linux }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-24.04
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: aarch64

    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable

      - name: Use Wild linker
        uses: davidlattimore/wild-action@latest

      - uses: snok/install-poetry@v1

      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install and cache apt pkgs
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: flatpak flatpak-builder libglib2.0-dev libsecret-1-dev libgtk-3-dev libpng-dev libjpeg-dev libgl1-mesa-dev libglu1-mesa-dev libxkbcommon-dev libexpat1-dev libtiff-dev libxdo-dev libappindicator3-dev
          version: 1.0

      - name: Build binaries
        run: make linux PROFILE=release APPIMAGE=1

      - name: Upload binaries
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.BINARY_NAME }}-linux-${{ matrix.arch }}
          path: dist/*
          if-no-files-found: error

  build-windows:
    if: ${{ github.event_name == 'push' || inputs.build_windows }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            arch:
